packages: []
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@oxc-project/types@0.152.0'
  - '@rolldown/binding-android-arm-eabi@1.2.12'
  - '@rolldown/binding-android-arm64@1.2.12'
  - '@rolldown/binding-darwin-arm64@1.2.12'
  - '@rolldown/binding-darwin-x64@1.2.12'
  - '@rolldown/binding-freebsd-x64@1.2.12'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.12'
  - '@rolldown/binding-linux-arm64-gnu@1.2.12'
  - '@rolldown/binding-linux-arm64-musl@1.2.12'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.12'
  - '@rolldown/binding-linux-s390x-gnu@1.2.12'
  - '@rolldown/binding-linux-x64-gnu@1.2.12'
  - '@rolldown/binding-linux-x64-musl@1.2.12'
  - '@rolldown/binding-openharmony-arm64@1.2.12'
  - '@rolldown/binding-win32-arm64-msvc@1.2.12'
  - '@rolldown/binding-win32-x64-msvc@1.2.12'
  - rolldown@1.2.12
  - vite@8.3.1
overrides:
  rolldown: 1.2.12
  unbash: 4.0.11
